// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooBuilderBackend.Data;

#nullable disable

namespace ZooBuilderBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250331113135_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooBuilderBackend.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attraction")
                        .HasColumnType("integer");

                    b.Property<int>("Costs")
                        .HasColumnType("integer");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Hunger")
                        .HasColumnType("integer");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Animal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attraction = 5,
                            Costs = 15,
                            Diet = "Meat",
                            Hunger = 4,
                            Species = "Lion"
                        },
                        new
                        {
                            Id = 2,
                            Attraction = 4,
                            Costs = 12,
                            Diet = "Vegetables",
                            Hunger = 3,
                            Species = "Giraffe"
                        },
                        new
                        {
                            Id = 3,
                            Attraction = 5,
                            Costs = 20,
                            Diet = "Vegetables",
                            Hunger = 4,
                            Species = "Elephant"
                        },
                        new
                        {
                            Id = 4,
                            Attraction = 2,
                            Costs = 8,
                            Diet = "Fish",
                            Hunger = 2,
                            Species = "Penguin"
                        },
                        new
                        {
                            Id = 5,
                            Attraction = 4,
                            Costs = 12,
                            Diet = "Vegetables",
                            Hunger = 2,
                            Species = "Kangaroo"
                        },
                        new
                        {
                            Id = 6,
                            Attraction = 3,
                            Costs = 10,
                            Diet = "Vegetables",
                            Hunger = 3,
                            Species = "Zebra"
                        },
                        new
                        {
                            Id = 7,
                            Attraction = 5,
                            Costs = 18,
                            Diet = "Bamboo",
                            Hunger = 2,
                            Species = "Panda"
                        },
                        new
                        {
                            Id = 8,
                            Attraction = 1,
                            Costs = 3,
                            Diet = "Meat",
                            Hunger = 1,
                            Species = "Rat"
                        });
                });

            modelBuilder.Entity("ZooBuilderBackend.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("Costs")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRevenue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SizeHeight")
                        .HasColumnType("integer");

                    b.Property<int>("SizeWidth")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("Building");
                });

            modelBuilder.Entity("ZooBuilderBackend.Models.GridPlacement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalCount")
                        .HasColumnType("integer");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<bool>("Connected")
                        .HasColumnType("boolean");

                    b.Property<int>("XCoordinate")
                        .HasColumnType("integer");

                    b.Property<int>("YCoordinate")
                        .HasColumnType("integer");

                    b.Property<int>("ZooId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("ZooId");

                    b.ToTable("GridPlacement");
                });

            modelBuilder.Entity("ZooBuilderBackend.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("ZooBuilderBackend.Models.Zoo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Money")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Vegetables")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Zoo");
                });

            modelBuilder.Entity("ZooBuilderBackend.Models.Building", b =>
                {
                    b.HasOne("ZooBuilderBackend.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("ZooBuilderBackend.Models.GridPlacement", b =>
                {
                    b.HasOne("ZooBuilderBackend.Models.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId");

                    b.HasOne("ZooBuilderBackend.Models.Zoo", "Zoo")
                        .WithMany("GridPlacements")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("ZooBuilderBackend.Models.Zoo", b =>
                {
                    b.HasOne("ZooBuilderBackend.Models.Player", "Player")
                        .WithMany("Zoos")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ZooBuilderBackend.Models.Player", b =>
                {
                    b.Navigation("Zoos");
                });

            modelBuilder.Entity("ZooBuilderBackend.Models.Zoo", b =>
                {
                    b.Navigation("GridPlacements");
                });
#pragma warning restore 612, 618
        }
    }
}
