name: CI

on: 
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.401'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: Backend/ZooBuilderBackend

      - name: Build
        run: dotnet build --no-restore
        working-directory: Backend/ZooBuilderBackend
  
      - name: Verify test project exists
        run: ls -la Backend/ZooBuilderBackend/ZooBuilderBackend.Tests/

      - name: Test
        run: dotnet test ZooBuilderBackend.Tests/ZooBuilderBackend.Tests.csproj --verbosity normal --logger:trx
        working-directory: Backend/ZooBuilderBackend
  
  frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Unity
        uses: webbertakken/unity-actions/setup@v2
        with:
          unityVersion: 2022.3.21f1

      - name: Test Unity
        uses: webbertakken/unity-actions/test-runner@v2
        with:
          unityVersion: 2022.3.21f1
          testMode: playmode
          artifactsPath: results